Future-House/ldp

ldp/alg/runners.py
I realized `num_rollouts_per_env` was duplicated across `EvaluatorConfig` and `OnlineTrainerConfig`
=> Removed duplicated `num_rollouts_per_env`

ldp/alg/callbacks.py, ldp/data_structures.py, ldp/graph/async_torch.py, ldp/graph/ops.py
1. `TrajectoryFileCallback` changes assumed that all envs implemented `export_frame()`; this loosens that assumption
2. Serializing logprobs when dumping `OpResult`s
=> Suppress env frame errors; serialize logprob

ldp/alg/rollout.py, ldp/utils.py, tests/test_utils.py
Currently, when we run a rollout and the environment fails, the reason for failure is not included in the traceback. Instead we get the following unhelpful traceback
```
Traceback (most recent call last):
File "aviary-internal/.venv/lib/python3.12/site-packages/ldp/alg/rollout.py", line 42, in reraise_exc_as
yield
File "aviary-internal/.venv/lib/python3.12/site-packages/ldp/alg/rollout.py", line 229, in _rollout
obs, tools = await env.reset()
^^^^^^^^^^^^^^^^^
File "aviary-internal/.venv/lib/python3.12/site-packages/aviary/env_client.py", line 102, in reset
return await super().reset()
^^^^^^^^^^^^^^^^^^^^^
File "aviary-internal/.venv/lib/python3.12/site-packages/aviary/env_client.py", line 46, in reset
response = await self._post(
^^^^^^^^^^^^^^^^^
File …
```
=> Better HTTP Error Handling

ldp/agent/simple_agent.py
`SimpleAgent`'s docstring had this comment:
> It does not have a system prompt because it's meant to be lightweight.
Which is actually incorrect (it does have a `sys_prompt`, just it's not learnable), so I removed it.
=> Removed incorrect `SimpleAgent` description in docstring

ldp/alg/callbacks.py, ldp/data_structures.py, tests/test_rollouts.py
This PR:
- Dumps all files in `async` via `aiofiles`, resolving a TODO comment
- Allows for control over `Environment.Frame` dump
- Makes attribute names more intuitive
=> `TrajectoryFileCallback` having `async` file I/O and controlling `Environment` dump

ldp/agent/__init__.py, ldp/agent/react_agent.py, ldp/agent/simple_agent.py, ldp/agent/tree_of_thoughts_agent.py, tests/__init__.py, tests/cassettes/TestLLMCallOp.test_compute_logprob[0.0].yaml, tests/cassettes/TestLLMCallOp.test_compute_logprob[0.5].yaml, tests/cassettes/TestLLMCallOp.test_compute_logprob[1.0].yaml, tests/cassettes/TestReActAgent.test_multi_step[False].yaml, tests/cassettes/TestReActAgent.test_multi_step[True].yaml, tests/test_agents.py, tests/test_envs.py, tests/test_modules.py, tests/test_ops.py, tests/test_optimizer.py
=> Incorporating `llmclient.CommonLLMNames`

ldp/data_structures.py
A method to create a tree with only terminal branches
=> `remove_nonterminal_branches`

ldp/graph/common_ops.py, tests/cassettes/TestLLMCallOp.test_validation.yaml, tests/test_ops.py
This PR implements user-specified response validation for `LLMCallOp` with retries. I've implemented a validator for mangled tool calls from Anthropic, but one could also use this for rejection sampling, etc. 
I toyed around with a couple other places to put this (`llmclient.LiteLLMModel`, `SimpleAgent`), but found this to be most natural and easiest to configure. Ideally I'd have liked to implement this as a `litellm` callback, but I don't think their retry mechanism is triggered by callback exceptions.
=> LLM response validation

ldp/alg/algorithms.py
When you type it correctly, there's no need for `cast`
=> Fixing `evaluate_consensus`'s `extract_answer_fn` typing

ldp/nn/agent/simple_local_agent.py, ldp/nn/generation/__init__.py, ldp/nn/generation/base.py, ldp/nn/graph/llm_call_op.py, ldp/nn/handlers/transformer_handler.py
Missed a couple things in #217 :
- Ability to pass in arbitrary call kwargs
- Support for a custom logit processor base class that can be finalized post-generation. The implementations will come in a subsequent PR.
=> Local LLM call arguments

ldp/nn/handlers/transformer_handler.py
`dask_jobqueue` cannot be started in a subprocess, so making it a lazy import.
=> Import dask_jobqueue lazily

packages/lmi/README.md
The documentation on readme had some comments suggesting that the limits applied to the `rate_limiter` were requests per minute. However, `lmi` only controls TPM for now. This PR fixes the wording.
=> Fix wrong comment saying that lmi can control RPM

packages/lmi/pyproject.toml, uv.lock
Pulling in https://github.com/BerriAI/litellm/pull/8963, which also removes the need for the `deepseek` extra (since we now pin a LiteLLM beyond it.
=> Pinned `litellm` for reasoning + streaming fix, dropped `deepseek` extra

packages/lmi/src/lmi/rate_limiter.py, uv.lock
`limits` changed how to get the `PREFIX` from `RedisStorage` on version 4.2.
We're getting it directly from the class now
=> Used PREFIX from RedisStorage instead of using it from the instance

.gitignore, src/ldp/alg/rollout.py, src/ldp/graph/async_torch.py, src/ldp/nn/agent/simple_local_agent.py, src/ldp/nn/handlers/chunking.py, src/ldp/nn/handlers/transformer_handler.py, tests/test_nn_models.py
Reverts #231 
We can no longer see the original stack trace of a caught exception - this makes debugging difficult. Reverting until this is understood.
```
ldp.graph.common_ops.LLMCallOp._call_single_and_maybe_validate() got multiple values for keyword argument 'model'
Traceback (most recent call last):
File "/Users/ryan-rhysgriffiths/miniconda3/envs/aviary4/lib/python3.12/site-packages/ldp/alg/rollout.py", line 333, in _rollout
step = await self._take_step(timestep, traj_id, env, agent_state, obs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ryan-rhysgriffiths/miniconda3/envs/aviary4/lib/python3.12/site-packages/ldp/alg/rollout.py", line 387, in _take_step
with reraise_exc_as(AgentError, enabled=self.catch_agent_failures):
File …
```
=> Revert "Rollout Manager & Chunking Improvements"

.secrets.allowlist, packages/lmi/src/lmi/llms.py, src/ldp/graph/common_ops.py, tests/cassettes/test_fallbacks_working[False].yaml, tests/cassettes/test_fallbacks_working[True].yaml, tests/test_rollouts.py
We re-use our agent's input `llm_model` configuration in both the `LLMModel` instantiation and in our `call` kwargs. These have some overlapping, but otherwise different arguments. We could split these into different configs, but this would be a big LDP change because it changes the call signature on an LLM op's forward function. 
So, we're just making this such that an Agent can actually define an llm configuration and not break if any inputs are being used for the router config which aren't supported as `call` kwargs. 
As a little clean up -- 🧹  we had a couple places with mutated kwargs, I am using deep copies to fix this.
=> Allow agent fallback configuration

.github/renovate.json5
See PR title
https://github.com/Future-House/ldp/pull/176 missed removing Renovate's <= Python 3.12 constraint
=> Updating Renovate config to allow Python 3.13 but downpin `torch<2.6`

packages/lmi/src/lmi/embeddings.py, packages/lmi/src/lmi/llms.py, packages/lmi/tests/cassettes/TestLiteLLMEmbeddingModel.test_router_usage[with-router].yaml, packages/lmi/tests/cassettes/TestLiteLLMEmbeddingModel.test_router_usage[without-router].yaml, packages/lmi/tests/test_embeddings.py
Currently, embeddings just call litellm and thus don't provide the same configuration possibilities as the other completion endpoints. To fix this, a router is now used similar to the other calls so that one can use eg the following for azure-hosted:
```python
embedding = "text-embedding-3-small"
embedding_config = {
"model_list": [
{
"model_name": embedding,
"litellm_params": {
"model": "azure/text-embedding-3-small",  # azure/<your deployment name>
"api_key": os.getenv("AZURE_API_KEY"),
"api_version": "2024-04-01-preview",
"api_base": os.getenv(
"AZURE_API_BASE"
),  # eg. https://openai-gpt-4-test-v-1.openai.azure.com/
},
},
]
}
```
=> Use router also for embeddings

packages/lmi/src/lmi/embeddings.py
Due to our CI not working for forks, this mistake evaded my attention there (as I was only running `test_router_usage`)
=> Restored explicit `"model_list"` check I'd removed in #280

packages/lmi/src/lmi/embeddings.py, packages/lmi/tests/cassettes/TestLiteLLMEmbeddingModel.test_embedding_batches.yaml, packages/lmi/tests/test_embeddings.py, packages/lmi/tests/test_rate_limiter.py
Previously `LiteLLMEmbeddingModel`:
- `embed_documents` relied on a batch size keyword argument, inconsistent with its parent class
- `SentenceTransformerEmbeddingModel` pulls batch size from `config`
- Had a one-off `batch_size` attribute, not configurable from `paper-qa`: https://github.com/Future-House/paper-qa/blob/v5.21.0/paperqa/llms.py#L575-L584
This PR fixes both of these, with a test
=> `LiteLLMEmbeddingModel` configurable `batch_size`

packages/lmi/src/lmi/utils.py
I found the logs in https://github.com/Future-House/paper-qa/tree/v5.23.0 to be super noisy, so this PR just suppresses a few more.
=> Suppressing more loggers for LLMs

.github/workflows/publish.yml
Propagating https://github.com/Future-House/aviary/pull/260 to this repo
=> Fixing `publish` job for `uv>=0.8`

packages/lmi/src/lmi/cost_tracker.py, packages/lmi/tests/test_cost_tracking.py
Making the callbacks in cost_tracker.py asynchronous: job-event calls run after every LLM request, so we schedule them on the event loop to avoid blocking the main execution path and adding latency.
=> Make the callbacks in cost_tracker async

src/ldp/agent/react_agent.py, src/ldp/agent/simple_agent.py, src/ldp/utils.py, tests/test_agents.py, tests/test_utils.py
Some environments might not need to keep track of all the previous messages history (e.g. envs that keep a plan in the env state and keep updating it).
This PR allows agents to define a sliding window to only keep in context the last N chat transitions.
=> Add support for a messages sliding window
