- ldp/alg/callbacks.py
Closes https://github.com/Future-House/ldp/issues/195
> Removed unnecessary `before_transition` from `TrajectoryFileCallback`

- ldp/agent/__init__.py
> Added forgotten `DEFAULT_LLM_COMPLETION_TIMEOUT` to `agent.__all__`

- ldp/alg/__init__.py
- ldp/alg/algorithms.py
- tests/test_algorithms.py
> Added 'pass @ k' to alg

- ldp/alg/algorithms.py
Coming from https://github.com/Future-House/ldp/pull/202#discussion_r1906114284
> Documenting exact figures/equations for 'pass @ k' alg

- ldp/alg/runners.py
- ldp/data_structures.py
- tests/test_runners.py
> Add num_epochs to OfflineTrainer

- ldp/agent/__init__.py
- ldp/agent/simple_agent.py
- tests/cassettes/TestNoToolsSimpleAgent.test_dummyenv[claude-3-haiku-20240307].yaml
- tests/cassettes/TestNoToolsSimpleAgent.test_dummyenv[gpt-4o-mini-2024-07-18].yaml
- tests/test_agents.py
This is a `SimpleAgent` subclass that:
1. Prompts the LLM without and tools in the schemae
2. Casts the resultant response `Message` into a `ToolRequestMessage`
> Created `NoToolsSimpleAgent`

- CITATION.cff
Sister PR to https://github.com/Future-House/aviary/pull/180
> Added a `CITATION.cff`

- ldp/nn/handlers/transformer_handler.py
`dask_cuda` only works on Linux
> Make dask_cuda import lazy

- ldp/nn/lm_config.py
I want more fine-grained control
> Explicit pad token configuration

- ldp/agent/simple_agent.py
- tests/cassettes/TestSimpleAgent.test_hide_old_action_content.yaml
- tests/test_agents.py
> Add hide_old_action_content

- ldp/graph/ops.py
- tests/cassettes/TestHTTPAgentClient.test_lifecycle.yaml
> Fixed `OpResult` deserialization by discarding `logprob` after #197

- LICENSE
- packages/lmi/LICENSE
> Added LICENSE to lmi

- packages/lmi/pyproject.toml
- uv.lock
SEE: https://github.com/BerriAI/litellm/issues/8939
> Upper-pinned LiteLLM for reasoning + `stream` regression

- .github/workflows/tests.yml
I realized this today, and it's awesome
> Simplified `refurb` in CI after #238 fixed `mypy` config

- src/ldp/graph/loss_ops.py
- src/ldp/nn/graph/llm_call_op.py
I was investigating if we can make this an optional dependency, turns out we can't.
> Moved a few `tree` imports to `TYPE_CHECKING`

- README.md
- packages/lmi/README.md
Our public repos follow different badge patterns. It became more evident with the cookbook. 
Now that we are linking the platform documentation to the platform and plan to release it, the cookbook will see more traffic. This PR (together with similar ones on other repos) fixes it.
> Updated repo badges

- packages/lmi/tests/cassettes/TestLiteLLMModel.test_call_w_multiple_models[multiple-models].yaml
- packages/lmi/tests/test_llms.py
This PR addresses @jamesbraza and @mskarlin comments on #277 . 
It passes an invalid key to trigger the fallback to make the test more realistic.
> Forced fallback passing an invalid key instead of mocking the return

- packages/lmi/pyproject.toml
- packages/lmi/src/lmi/rate_limiter.py
- uv.lock
Accounting for https://github.com/alisaifee/limits/compare/4.7.3...4.8.0 's change to `RedisBridge.PREFIX`
> Pulling in latest `limits`

- pyproject.toml
- tests/test_agents.py
- uv.lock
> Pulled in latest `fhaviary` for tool schemae changes

- README.md
> Fixing dead link in README

- packages/lmi/pyproject.toml
- pyproject.toml
> Added missing PyPI classifiers

- README.md
- tutorials/creating_a_language_agent.ipynb
Minor update tutorial ipynb and readme link.
> Minor update tutorial ipynb and readme link

- pyproject.toml
- src/ldp/alg/beam_search.py
- src/ldp/alg/rollout.py
- src/ldp/data_structures.py
- tests/test_rollouts.py
- uv.lock
Adding trajectory-level metadata adds traceability to the system and can enable majority voting schemes.
> `Trajectory` storing `Environment`'s ID

- packages/lmi/src/lmi/utils.py
- packages/lmi/tests/conftest.py
- tests/conftest.py
Adding a workaround for https://github.com/BerriAI/litellm/issues/9792
> Helper function to defeat `litellm`'s `MAX_CALLBACKS` error

- packages/lmi/README.md
> Removed `batch_size` mention in docs missed by #301

- packages/lmi/README.md
I keep forgetting how to do this, so added it to README
> Add notes about vertex to README

- packages/lmi/tests/test_embeddings.py
- src/ldp/alg/optimizer/memory.py
- uv.lock
I observed a unit test from https://github.com/Future-House/ldp/pull/280 had missed an `assert`
> Pulled in latest `mypy` for missing `assert`

- src/ldp/agent/simple_agent.py
- tests/test_agents.py
This PR fixes 2 issues from https://github.com/Future-House/ldp/pull/336
It also adds a unit test, which the previous PR probably should have included.
> Sliding window support fixes

- src/ldp/graph/modules/react.py
- tests/cassettes/TestAgentState.test_no_state_mutation[agent2].yaml
- tests/cassettes/TestReActAgent.test_agent_grad[False-claude-3-5-haiku-20241022].yaml
- tests/cassettes/TestReActAgent.test_agent_grad[False-gpt-4o].yaml
- tests/cassettes/TestReActAgent.test_multi_step[False].yaml
- tests/cassettes/TestReActAgent.test_react_dummyenv[False-claude-3-5-haiku-20241022].yaml
- tests/cassettes/TestReActAgent.test_react_dummyenv[False-gpt-4o].yaml
We were formatting the ReAct message to show the "Though: ... Action: ..." process in the message history. Because we added a period to this message, it resulted in a duplication in the final message (check image). This PR removes this duplication and simplified the message to avoid having this same template repeated all over
```
Based on this reasoning, let's select the appropriate tool!"
Action: "
```
> Reduced the react text and duplicated period

- packages/lmi/pyproject.toml
- packages/lmi/tests/conftest.py
- packages/lmi/tests/test_rate_limiter.py
- pyproject.toml
- src/ldp/agent/agent_client.py
- tests/cassettes/TestReActAgent.test_agent_grad[False-claude-3-5-haiku-20241022].yaml
- tests/cassettes/TestReActAgent.test_react_dummyenv[False-claude-3-5-haiku-20241022].yaml
- tests/conftest.py
- tests/test_agents.py
- uv.lock
Sister PR to https://github.com/Future-House/aviary/pull/287
> Migrating `httpx.AsyncClient` to `httpx_aiohttp.HttpxAiohttpClient`
